# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
