# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0007_auto_20170926_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.DateTimeField(),
        ),
    ]
