# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0012_auto_20171009_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barber_Salon',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
