# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0015_auto_20171010_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploadphoto',
            field=models.FileField(default=None, null=True, upload_to='wavesapp/profile.html'),
        ),
    ]
