# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wavesapp', '0022_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.AddField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wavesapp.Gallery'),
        ),
    ]
