# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0023_auto_20171016_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='due_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='time_of_appointment',
            field=models.TimeField(default=None, null=True),
        ),
    ]
