# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0024_auto_20171016_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='profile_photos'),
        ),
    ]
