# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0028_gallery_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
