# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wavesapp', '0029_auto_20171018_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='company_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wavesapp.Profile'),
        ),
    ]
