# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171018_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Profile',
            new_name='profile',
        ),
    ]
